### PR TITLE
FIX: select folder callback error on mac

### LINKED ISSUE #29: Selection of a directory in dash
The current code used to select a folder has multiple issues (does not work on MacOS, open the window in background). It is unclear that it is a good idea to use TkInter in combination with Dash.

Issues with threads interfering with one another has been reported at multiple places, e.g., here: https://community.plotly.com/t/core-component-allow-select-folder/14955/11

Maybe the TkInter issues can be solved (https://stackoverflow.com/questions/67702316/combining-plotly-dash-with-a-tkinter-gui-dash-forces-to-execute-the-tk-mainloo) but I am unsure that it will provide a robust solution. Maybe a native Dash solution would be preferable.

A folder selection dash-core-component has been asked for in 2019 and upvoted multiple times, but without apparently having caught the attention of the developers: https://github.com/plotly/dash-core-components/issues/639

Other relevant links:
- https://discourse.julialang.org/t/with-dash-how-to-obtain-a-directory-name-from-a-file-browser/65826

### PR DESCRIPTION
**Pull request by scott-huberty**
Fixes #29 

This works on my mac. Fixes the error we were getting by using the `multiprocessing` module to ~~keep the process in the main thread~~ execute this action in a separate process.

- [x] I'll test this out on my windows computer tomorrow morning. (UPDATE: Works).

@christian-oreilly Can you review/pull this branch and test it out on your side?  (NOTE: this branch is on the lina-usc remote, NOT my fork.)

### CODE REVIEW

**Comment by scott-huberty** [comment]
> Folder loading works fine on my side too! 

Awesome!!! and agreed, that is a good idea.

**Comment by scott-huberty** [comment]
@Andesha would you mind pulling this branch and trying out the select folder button, on your Linux computer?

**Comment by Andesha** [comment]
can confirm this works for me

**Comment by scott-huberty** [comment]
awesome! I am going to rebase with main and merge.

**Pull request merged**
