### PR TITLE
Fix first pass of linting errors

### PR DESCRIPTION
**Pull request by Andesha**
As per #66 .

I've decided to wait on fixing some of the larger blocks of linting errors until everything is back into main.

It's more than likely that those will take some larger structural changes so best to get stable first.

### CODE REVIEW

**Comment by scott-huberty** [comment]
got it.. so in that case @Andesha I will merge #61 and we can handle any conflicts here (if they pop up).

**Comment by Andesha** [comment]
yeah, that's for the best

I should also work on testing the QC for myself so that I can make sure I am not breaking things

**Comment by scott-huberty** [comment]
I'll pull your branch and test it as well.

**Comment by scott-huberty** [comment]
I'm looking at the conflicts now.

**Comment by scott-huberty** [comment]
I Fixed the conflicts and launched the dashboard locally. Everything appears to work fine!

**Comment by Andesha** [comment]
I'm still having a couple of issues with the dashboard but I pulled in your changes and did another wave of linting.

Only thing left is the `mne_visualizer.py` file, which I'm going to leave alone for a bit as I think it needs less nesting after the next set of bug fixes...

**Comment by Andesha** [comment]
Just pushed another wave of fixes - should be good to go

**Comment by scott-huberty** [comment]
LGTM. 

Just pushed an empty commit so we can verify that CI's pass.

Maintenance note: `flake8` linting is passing in the dash module, some docstring formatting still needed for Numpy doc compliance, will circle back on follow up PR.

**Pull request merged**
