### PR TITLE
CI: Try deploying dasbhoard upon pull request

### PR DESCRIPTION
**Pull request by scott-huberty**

### CODE REVIEW

**Comment by christian-oreilly** [comment]
Out of curiosity, what happened with this? Did you abandon the idea?

**Comment by scott-huberty** [comment]
> Out of curiosity, what happened with this? Did you abandon the idea?

ugh... I cannot believe how convoluted it is just to deploy a Python dash app to these cloud services. 

I am not a CS engineer but I also like to think that I generally know my way around bash/dev ops stuff.

Right now I am just focusing on getting `pylossless_qc` to deploy to a server from my local computer. Once I have an idea of how to do this, I'll return to integrating that into CI, probably from a fresh branch.

**Comment by christian-oreilly** [comment]
Sure! As I was saying, it was more out of curiosity than anything else.

> Right now I am just focusing on getting pylossless_qc to deploy to a server from my local computer. 

Well, I think you know how to do that: running `pylossless_qc` in the terminal does just that (i.e., it creates a local http server and makes it accessible through a local IP)! Maybe you mean "how to deploy a local server through your publically accessible IP rather than a local address"?

Maybe this post can help https://community.plotly.com/t/accessing-dash-webserver-from-hosts-other-than-localhost/4675 ?

> app.run(host= ‘0.0.0.0’)
> to make flask an Externally Visible Server

**Comment by christian-oreilly** [comment]
Also, I supposed you saw this for Heroku dash? https://dash.plotly.com/deployment?_ga=2.2231222.748729490.1682966262-1036184451.1673051298

**Comment by scott-huberty** [comment]
> Also, I supposed you saw this for Heroku dash? https://dash.plotly.com/deployment?_ga=2.2231222.748729490.1682966262-1036184451.1673051298

Yeah. These cloud services try to strip away complexity by just expecting your dash app to be named `app.py` and be located at the root of the directory, which they will just try to launch by default.

Our case is more complex and we need to specify the VM to run `pylossles_qc` which is the tricky part. I think we'll need to utilize a docker image.

**Comment by christian-oreilly** [comment]
Why not just creating a symlink app.py at the root?

**Pull request closed without merging**
